<?php defined('SKYBLUE') or die(basename(__FILE__)); ?>

[STATES]

states[] = alabama
states[] = alaska
states[] = american samoa
states[] = arizona
states[] = arkansas
states[] = california
states[] = colorado
states[] = connecticut
states[] = delaware
states[] = district of columbia
states[] = federated states of micronesia
states[] = florida
states[] = georgia
states[] = guam
states[] = hawaii
states[] = idaho
states[] = illinois
states[] = indiana
states[] = iowa
states[] = kansas
states[] = kentucky
states[] = louisiana
states[] = maine
states[] = marshall islands
states[] = maryland
states[] = massachusetts
states[] = michigan
states[] = minnesota
states[] = mississippi
states[] = missouri
states[] = montana
states[] = nebraska
states[] = nevada
states[] = new hampshire
states[] = new jersey
states[] = new mexico
states[] = new york
states[] = north carolina
states[] = north dakota
states[] = northern mariana islands
states[] = ohio
states[] = oklahoma
states[] = oregon
states[] = palau
states[] = pennsylvania
states[] = puerto rico
states[] = rhode island
states[] = south carolina
states[] = south dakota
states[] = tennessee
states[] = texas
states[] = utah
states[] = vermont
states[] = virgin islands
states[] = virginia
states[] = washington
states[] = west virginia
states[] = wisconsin
states[] = wyoming